### ISSUE TITLE
Suggestion: Unify with & add DuckDuckGo !bang conventions

### ISSUE THREAD

**Issue by KZeni** [arnemart/SafariKeywordSearch#1]
DuckDuckGo has a very similar offering to this with its !bang feature. You can see more about it & also look at what !bang options are currently available at https://duckduckgo.com/bang

When it comes to existing DDG !bang search commands, I'm wondering if the default set of commands in Keyword Search should match what DDG has to help remove any friction between the two. Also, this has a nice set of sites with search which could be helpful for reference to add to Keyword Search's default set, when appropriate.

I know, people could just use !bang commands by using DDG, but it could be nice if the two worked together nicely for those that might not be using DDG so the transition between the two is smoother.

Just an idea that I wanted to put out there.

Thanks for the great extension 😄

**Comment by jakecast** [comment]
Having used both, I honestly prefer the default style of Safari Keyword Search. a lot easier for me to type `gi` in front of something instead of suffixing it with an exclamation point and another string for some reason. Maybe its pain of hitting ⇧+1 after something.
Just my personal opinion though!

**Comment by KZeni** [comment]
@jakecast True. Might be a case where they can match except for the `!` at the start for Keyword Search's implementation.

**Comment by arnemart** [comment]
Thanks for the suggestion, but I think I'll stick to how it is now. I think DDG has several hundred !bang expansions, adding all those is not really feasible, and I prefer my keywords to the ones DDG uses. Nothing is stopping you from using DDG as your default search engine with this extension enabled however, then you can mix and match as you please.
