### ISSUE TITLE
Extension does not appear in safari

### ISSUE THREAD

**Issue by 3rikk** [arnemart/SafariKeywordSearch#10]
Hey all
The extension dosen't appear in safari's extension list upon install. Im not sure if this is the same issue as #7  , as this is my first install and the extension hadn't worked beforehand.

(M1 MacBook Air, macOS 11.3 non-beta, Safari 14.1)

Thanks :)

**Comment by m-schmitt** [comment]
Same issue, but on Intel MacBook Pro, macOS 10.15.7 Catalina, Safari 13.1.3.

**Comment by m-schmitt** [comment]
Works for me after updating Safari to 14.1.1.

**Comment by arnemart** [comment]
I think this is the same as https://github.com/arnemart/SafariKeywordSearch/issues/7
