### ISSUE TITLE
Keyword working even if it's not in the beginning of the string.

### ISSUE THREAD

**Issue by michellekg** [arnemart/SafariKeywordSearch#12]
I discovered a strange bug - all keywords are working even if they are not in the beginning of the string but even in the end for example.

Fore example, "my grade is an a" works like "a my grade is an" - it looks "my grade is an" on Amazon. Sometimes it's very inconvenient, especially with my own keywords.

Can you please restrict Keyword Search so that keywords can be only at the beginning of the string?

**Comment by shawnrc** [comment]
This is a feature, actually, but I really dislike the fact it's enabled by default, would appreciate a toggle or something

**Comment by michellekg** [comment]
> This is a feature, actually, but I really dislike the fact it's enabled by default, would appreciate a toggle or something

Oh, wow. Yes, a toggle would be nice.

**Comment by michellekg** [comment]
Well, now I can't even search for, like, "ebay" in Google.com, because Google puts this word in the search string and it triggers Keyword Search. Pretty please, fix this bug!

**Comment by arnemart** [comment]
Version 2 will be out extremely shortly, the new default behavior is to only allow keywords at front but there is a setting to override it globally and also for each keyword.
