### ISSUE TITLE
Minus character breaks trigger

### ISSUE THREAD

**Issue by BNolet** [arnemart/SafariKeywordSearch#13]
Trying to perform the search of some sort of asset tag (say "INF-001166") results in the trigger failing to...trigger. It will just default to making a Google search

**Comment by arnemart** [comment]
Hm, I have not been able to reproduce this. Have you tried it in the new 2.0 version?

**Comment by arnemart** [comment]
Gonna close this issue for now, please let me know if it keeps happening.
