### ISSUE TITLE
unexplained failure

### ISSUE THREAD

**Issue by sstadelman** [arnemart/SafariKeywordSearch#15]
Extension has been working fabulously for 3 months, then suddenly died this morning.  My shortcuts fail to be recognized in the searchbar, and clicking on the details view shows a 'Loading' dialog. 

<img width="183" alt="Screen Shot 2021-09-20 at 10 51 03 AM" src="https://user-images.githubusercontent.com/377404/134050361-ed188a9b-96aa-4aa2-8d97-4f49f1b18f8d.png">
  
I upgraded to Big Sur 11.6, Safari 14.1.2, does not resolve.  Any other reports of this?

**Comment by amja** [comment]
I had the same issue after the recent update. Tried uninstalling and reinstalling but this had no effect.

**Comment by sstadelman** [comment]
Fixed by update 2.0.3 via AppStore.  Thanks!!
