### ISSUE TITLE
iOS version not working

### ISSUE THREAD

**Issue by CartoonChess** [arnemart/SafariKeywordSearch#16]
Hello,

I've installed the new Safari extension for iOS 15, and while everything appears to be set up, none of the shortcuts trigger anything (e.g. `y Rick` simply does a Google search for exactly that). It also doesn't appear to sync up with the desktop version. Am I missing something or is this a known issue? Thanks!

**Comment by Joe00** [comment]
It works if you set the search engine to something else, like yahoo or bing

**Comment by CartoonChess** [comment]
Odd! Thanks for the workaround

**Comment by arnemart** [comment]
This is a known issue, and happens because you live in a country where google is on a different TLD than google.com! I have fixes this bug and it is on its way through app review right now, it will hopefully be out within a few hours.

**Comment by arnemart** [comment]
Fix is finally approved, update and it should work :-)
