### ISSUE TITLE
Review of v2: Finally works on first ENTER + Keyword on the end + Whitespace transformation

### ISSUE THREAD

**Issue by porg** [arnemart/SafariKeywordSearch#17]
Already reviewed you on the app store, here is a copy:

### ✅✅ Most importantly: The key functionality finally works reliably!
Keyword + query + ENTER leads me directly to the results. In v1.x the first ENTER often only submitted the entire query including keyword to my custom search engine, only on second press it worked. As of v2.0.2 this is now fixed.

### ℹ️ Some unique features for web browser searching
Per se this extension is not an over existing app or extension but just a practical utility/extension for improving for a feature which is neglected in Safari. But some clever extra features makes it stand out:

#### ✅ Keyword at the end of the query.
This is a custom feature which no other web browser yet offers! Great idea, b/c sometimes you phrase a query and only at the end realize to which search engine you want to send that to.

#### ✅ Whitespace transformation character

---

### Congratulations! And thanks for providing this!

The default search engine mechanism of Safari is well intended — a zero user management approach, where search engines automatically get added while browsing across them — but the end result is not efficient enough. This extension allows me to assign custom short keywords for my search engines. And with the added customizations it stands out from the rest!

**Comment by arnemart** [comment]
> Keyword + query + ENTER leads me directly to the results. In v1.x the first ENTER often only submitted the entire query including keyword to my custom search engine, only on second press it worked. As of v2.0.2 this is now fixed.

You do not want to know what kind of hoops I had to jump through to get this to work 😅 It can still partially happen, but it will only show the default search page for a second before navigating to the proper one.

Thanks a lot for the review and the nice feedback, I really appreciate it!
