### ISSUE TITLE
iCloud Sync - Lost custom searches

### ISSUE THREAD

**Issue by JonLaliberte** [arnemart/SafariKeywordSearch#20]
I assume this is due to the iCloud Sync.

I installed the extension on my iPad before updating to the latest release on my Mac.
Now all of the keywords/searches I had saved are gone. 
Any way to get those back?

**Comment by arnemart** [comment]
Not easily, sorry about that. The iCloud sync implementation is quite naively implemented, the latest edit always wins, so if you had upgraded on the Mac first it would have been OK but that’s small comfort now I guess. Apologies, hope this doesn’t turn you off using it.

**Comment by JonLaliberte** [comment]
Darn. It's fine though, I should have known better :)
I'll just set them back up. Thanks!

**Comment by arnemart** [comment]
I should have created a more robust syncing system but oh well 😅
