### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by Schweinepriester** [arnemart/SafariKeywordSearch#22]
Hello there!

Thanks for creating this great extension! :)

Would you consider [adding a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)?

I'd hope for a permissive one, but can understand if you are not going that route.

**Comment by arnemart** [comment]
Oh excellent point. I’ve been meaning to do that but have forgotten it, will do it tomorrow.

**Comment by arnemart** [comment]
5 days later, oh well. I went with the Mozilla Public License.
