### ISSUE TITLE
Support for Javascript Bookmarklets

### ISSUE THREAD

**Issue by porg** [arnemart/SafariKeywordSearch#23]
**Reproduction** to create a new bookmarklet which can be called via SafariKeywordSearch
- Click "Keyword Search" menu via address bar menu
- Click "Add new"
  - Name: `Google this domain`
  - Keywords: `gs`
  - Expansion: `javascript:void(location.href='https://www.google.com/search?q=@@@&domains='+location.hostname+'&sitesearch='+location.hostname)`
- Save

**Expected**: New entry gets created

**Actual**:
- Fails silently. No user feedback at all.
- Even if you won't support this kind of search, please at least fail with the form still open, marking the "Expansion" field red, and give a validation message "Unsupported URL scheme"

----

**Reproduction** in use: `dropmarkletKeyword query ENTER`

**Expected:** Executes the bookmarklet and sends you to the result

**Actual:** The full query with the keyword included is sent to the default search engine

----

https://user-images.githubusercontent.com/737143/135277853-3f2da1e7-1549-4253-bb0e-4480f780dfde.mp4

**Comment by arnemart** [comment]
Adding support for this would require giving the extension permission to read all the users web content, something I really don't want to do. I will look into it but I am probably going to add an error message if you try to save a javascript: url.

**Comment by porg** [comment]
Knowing now that a radical privacy loss is nessecary to achieve this, I agree it is not worth it!

But at least the error message instead of failing silently would be good.

**Comment by arnemart** [comment]
There was some bug in how form errors are handled when creating new custom searches, the upcoming version will not allow you to save unless the URL is a valid https?://-URL.
