### ISSUE TITLE
Support some Chinese searching engines

### ISSUE THREAD

**Issue by ice42cream** [arnemart/SafariKeywordSearch#25]
iOS in China offers three other searching engines:
[百度](https://www.baidu.com) 
[搜狗](http://www.sogou.com) 
[360搜索](http://www.so.com) 
They are more widely used than Google, etc in China and are not support by Keyword Search. Please consider support us.
![EED33509-50FC-42D6-9CDB-CE9AF530EDF3](https://user-images.githubusercontent.com/36615067/139568084-bd5c52dc-b164-4d87-85b9-0bf9bdb7e171.png)

**Comment by ice42cream** [comment]
Well, I am a first learner and I  spent some time trying to commit but I failed. 
I modified the file: SafariKeywordSearch/Shared (Extension)/Resources/background.js
for searchDomains, I added `'sogou.com': 'q',
  'www.sogou.com': 'q',
  'm.sogou.com': 'q',
  'baidu.com': 'q',
  'www.baidu.com': 'q',
  'so.com': 'q',
  'www.so.com': 'q',
  'm.so.com': 'q'`

**Comment by arnemart** [comment]
Looks like the parameter names are different these search engines, i.e. for baidu it should be `wd` instead of `q`. I will look into this and add support for these in an upcoming version, thanks for bringing it to my attention!

**Comment by ice42cream** [comment]
Thanks a lot. (I didn't notice `q` is the parameter name 🤣)
If you have any problem with Chinese, I will be pleased to offer my help.

**Comment by arnemart** [comment]
Sorry for being extremely slow with this, but support for all the default chinese search engines is now implemented and will I will submit a new version to the app store within the next few days
