### ISSUE TITLE
Export/Import

### ISSUE THREAD

**Issue by schmidhauser** [arnemart/SafariKeywordSearch#26]
Thank you very much for the extension. It’s extremely useful. 

I was wondering if you could add an export/import option in JSON. This would make it easy to backup, modify, and exchange one’s settings.

**Comment by arnemart** [comment]
This is on my todo list somewhere. Hopefully I will have time to release a new version in the not too distant future.

**Comment by arnemart** [comment]
Holy crap that took longer than I would have liked, but export/import is implemented in the latest version which will make its way to the app store quite soon, hopefully.
