### ISSUE TITLE
Default search engine / no keyword

### ISSUE THREAD

**Issue by jimeh** [arnemart/SafariKeywordSearch#29]
As Safari doesn't support changing the default search engine to something custom, I think it would be handy to allow setting a custom search engine for when no specific keyword is configured.

I've specifically ended up wanting this thanks to trying to use kagi.com as my default search engine. There is a [Safari extension](https://github.com/marcocebrian/kagisearchsafari), but it manages to take priority over Keyword Search, so all keyword searches just end up being searches on kagi.com with the keyword included.

Hence I'd prefer to use Keyword Search, but with the ability to point all non-keyword searches to kagi.com (or any custom search engine).

**Comment by aniqueta** [comment]
I came here to request exactly the same thing. This would be fantastic. I've been using the official [Kagi Search iOS app]([url](https://apps.apple.com/app/kagi-search-for-safari/id1607766153)) (across iOS and macOS). Keyword Search is noticeably faster (and open source), so it would be great to have this as a search engine replacement tool, as well as for the other keyword search functions as @jimeh notes. Hopefully straightforward to implement, as this would be simply applying the rewrite to all search queries regardless of keyword. Thank you!

**Comment by jimeh** [comment]
If it's of any help. For now I've ended up using a custom userscript that redirects DuckDuckGo searches to kagi. Most of the time it's fast enough that you don't even notice.

The userscript is in my dotfiles here: https://github.com/jimeh/dotfiles/blob/main/userscripts/kagi-for-safari.user.js

**Comment by aniqueta** [comment]
Thanks. Keyword Search seems to process these kinds of things faster, so this is good as a temporary solution. It would still be awesome if Keyword Search could implement what we're suggesting here.

**Comment by aniqueta** [comment]
@jimeh Did some testing and [xSearch](https://apps.apple.com/us/app/xsearch-for-safari/id1579902068) seems to be the fastest option right now across platforms, in case you're interested. It's paid and not open source, so still hope this becomes possible in this project in the future.

**Comment by nano9g** [comment]
I would love to have this feature too. Right now I'm using a URL redirect in StopTheMadness as a workaround.

@arnemart Is there any chance of this happening? Thanks so much!

**Comment by arnemart** [comment]
This feature is on its way to the app store right now!

**Comment by nano9g** [comment]
It works perfectly. Thank you so much!

**Comment by arnemart** [comment]
🙌
