### ISSUE TITLE
Space replacement character: Change is effective in query, but not shown in input field.

### ISSUE THREAD

**Issue by porg** [arnemart/SafariKeywordSearch#31]
# Reproduction
1. Open Keyword Search.
2. Open an entry, e.g. de.wikipedia.org
3. Open "Advanced Settings".
4. Space replacement character(s): I set an "_" underscore here. Saved. Even quitted Safari. Restarted. Reopened menu. Reopened entry.
- **Expected**: If I change the character(s) and save, they should also be shown here.
- **Actual**: The entered and saved character "_" is not shown here. But at least it is effective. Searches for "This thing" get's expanded to "This_thing" in the URL.

![Safari Keyword Search 1 opened menu](https://user-images.githubusercontent.com/737143/168820931-7f50241e-ec9d-44cb-9cb2-6752ea672ff4.png)
![Safari Keyword Search 2 scrolled down](https://user-images.githubusercontent.com/737143/168820591-dd055c4c-30ed-477f-a4ba-eb786ee6ffd6.png)
![Safari Keyword Search 2a entry top](https://user-images.githubusercontent.com/737143/168819664-0c6f19d0-8929-4fc6-9285-7eeb47be5d2e.png)
![Safari Keyword Search 2b entry bottom](https://user-images.githubusercontent.com/737143/168819668-9aec848e-1a24-4dcf-a14c-b624559f52f4.png)

**Comment by arnemart** [comment]
Thanks for the report! Silly bug on my part, it will be fixed in the upcoming release.

**Comment by porg** [comment]
👍 Glad that you could fix it!

**Offtopic but related**: The last screenshot shows that I indeed have needed "URL escape" in order for German Umlauts to work with Wikipedia queries. Which is what I documented in my PR https://github.com/arnemart/SafariKeywordSearch/pull/32#issuecomment-1673377418 which you sadly rejected. Please reconsider!
