### ISSUE TITLE
KeywordSearch just disappeared

### ISSUE THREAD

**Issue by thzch** [arnemart/SafariKeywordSearch#35]
Hi, 

Few days ago, the extension juste disappeared from safari preferences. 
I could'nt install it back.
Do you know know what could have caused this bug and how to fix it ?

Thank you

**Comment by simonmichael** [comment]
Maybe https://github.com/arnemart/SafariKeywordSearch#did-the-extension-disappear-from-safari-on-macos ?

**Comment by simonmichael** [comment]
And https://github.com/arnemart/SafariKeywordSearch/issues/27#issuecomment-1107456927

**Comment by thzch** [comment]
Thank you !
