### ISSUE TITLE
extension doesn't work in iPadOS 16 beta 11 (20B5064c)

### ISSUE THREAD

**Issue by AllForLandlord** [arnemart/SafariKeywordSearch#36]
After I updated my iPadOS to the newest developer beta, the extension doesn't work anymore. I tried to reboot my device but it doesn't help. Please fix the problem. Thank you very much!

**Comment by ColonelBuendia** [comment]
It’s most of the search modifying extensions, for anyone else banging their head against a wall all day today.  Same with  xSearch.  

Stop the madness’s url replace is still working though and ditto for Hyperweb.  Though they more regularly seem to load the original page before replacing it with the custom string and resulting search.

**Comment by AllForLandlord** [comment]
> It’s most of the search modifying extensions, for anyone else banging their head against a wall all day today. Same with xSearch.
> 
> Stop the madness’s url replace is still working though and ditto for Hyperweb. Though they more regularly seem to load the original page before replacing it with the custom string and resulting search.

That's pretty decent information! Thank you!
While still I hope the problem will be solved later😢

**Comment by AllForLandlord** [comment]
> It’s most of the search modifying extensions, for anyone else banging their head against a wall all day today. Same with xSearch.
> 
> Stop the madness’s url replace is still working though and ditto for Hyperweb. Though they more regularly seem to load the original page before replacing it with the custom string and resulting search.

I'm happy to say that in the newest beta for both iOS and iPadOS, which are "iOS 16.1 beta 5 (20B5072b) & iPadOS 16 beta 12 (20B5072b)", the problem has been solved. Now the extension works well again!

**Comment by ColonelBuendia** [comment]
Thank you!

**Comment by AllForLandlord** [comment]
Now I have updated my system to iOS 16.4 (20E5212f). And the extension stops working again. Hopefully it will be fixed in the next beta version!
