### ISSUE TITLE
extension doesn't work on iOS 16.4 (20E5212f)

### ISSUE THREAD

**Issue by AllForLandlord** [arnemart/SafariKeywordSearch#38]
I have updated my system to iOS 16.4 (20E5212f). And the extension stops working again. Hopefully it will be fixed automatically in the next beta version just like before

**Comment by neilio** [comment]
Confirming here, too.

**Comment by citizenunique** [comment]
Here too.
Also not working on macOS 13.3 Beta (22E5219e).

**Comment by AllForLandlord** [comment]
Update: I've updated system to the new beta version iPadOS 16.4 (20E5223e). Sadly, the problem still exists.

**Comment by ColonelBuendia** [comment]
Sadly it's the same story as from #36, nothing the app can do.  Beta builds of iOS keep doing this.  There are some mediocre workarounds in the mentioned issue, but in reality users of all the apps that offer this functionality are just waiting for next general release.

**Comment by AllForLandlord** [comment]
> Sadly it's the same story as from #36, nothing the app can do. Beta builds of iOS keep doing this. There are some mediocre workarounds in the mentioned issue, but in reality users of all the apps that offer this functionality are just waiting for next general release.

Yeah. Apple just released beta3. I will try to update to that and see if anything changes.

**Comment by neilio** [comment]
Works for me on iOS with yesterday's dev seed release, but still broken on macOS. The error on the Mac is "Keyword Search does not have permission to read, alter, or transmit content from any webpage".

**Comment by AllForLandlord** [comment]
> Works for me on iOS with yesterday's dev seed release, but still broken on macOS. The error on the Mac is "Keyword Search does not have permission to read, alter, or transmit content from any webpage".

Yeah I've just updated my system to that version as well and it fixed it. Case closed! Wait until next time we gather here again...
