### ISSUE TITLE
Toolbar Icon keeps reappearing in Safari

### ISSUE THREAD

**Issue by frankko** [arnemart/SafariKeywordSearch#4]
I have removed the Keyword Search button from my Safari toolbar. But it seems that after I open the Keyword Search main app to edit a search query or add a new query that causes the button to reappear in my toolbar.

Desired behavior: don’t resurrect the toolbar icon after it’s been manually removed.

macOS Big Sur 11.2.3 (20D91)
Safari 14.0.3 (16610.4.3.1.7)

**Comment by arnemart** [comment]
Weird. I have not explicitly added a toolbar button in the extension manifest, that may be what is causing this. In the next version (out shortly) I have specifically added a toolbar button that has actual functionality (it opens the settings app) that may fix it.

**Comment by arnemart** [comment]
1.0.2 is out now, does it fix this issue for you?

**Comment by dentalala** [comment]
On 1.0.2 the button keeps appearing.

**Comment by arnemart** [comment]
I'll keep this open for the next release then 😅

**Comment by frankko** [comment]
Yes, sorry, I can confirm that 1.0.2 didn’t solve the problem.

**Comment by arnemart** [comment]
It looks to me like getting rid of the button is not possible, the same applies to other safari extensions I am using as well. In any case the button is needed now in version 2 to access the search settings popover.
