### ISSUE TITLE
Problem when keyword is at the end

### ISSUE THREAD

**Issue by MPTres** [arnemart/SafariKeywordSearch#5]
the extension detects a keyword when it is found anywhere in the text typed in the safari bar, but it should only do it if the keyword is the first word.

For instance, if i type:
`extreme e`

it should just go to the default action without keyword and search it using the default safari engine.
Instead, the app detects the last "e" as the keyword, and searchs "extreme" in ebay.

Another example. If i search `ceo gm` looking for the ceo of general motors, it looks up "ceo" in google maps, instead of using safari's default search engine.

**Comment by arnemart** [comment]
This is a feature and not a bug, but I understand completely that some people might not want it. I will probably add a setting for this in a future update.

**Comment by MPTres** [comment]
a settings option would be great. thanks!!
