### ISSUE TITLE
Keyword detection in text fields in google and duckduckgo

### ISSUE THREAD

**Issue by MPTres** [arnemart/SafariKeywordSearch#6]
it seems that the extension is monitoring text fields in web pages, and performs a search if it detects a keyword there.

Way to reproduce it:

go to google.com or duckduckgo.com

Type `extreme e` in their search engine.  (in my computer 'e' is associated to ebay. you can try with other keywords)

Press enter or click search. Instead of searching in those web pages, the extension kicks in and redirects to ebay searching for term `extreme`.

It seems to happen in specific sites. For instance, it happens on google.com, but not in local sites like google.it or google.co.uk

edit: it also happens in bing.com

**Comment by arnemart** [comment]
Yeah sadly there is nothing I can do about this unless the extension API is changed. The extension has no access to what's actually being typed into the address bar (or into any textfields on any websites), and can only monitor when the URL changes. If the URL matches one of the default Safari search engines (duckduckgo, google, yahoo, bing, ecosia), the extension parses the URL and looks for a keyword in the search query parameter. If there were any other way of doing this I'd take it but this is sadly the only way the extension can work at this point.

**Comment by JonLaliberte** [comment]
@arnemart Would it be possible to configure the extension to only trigger when the keyword is at the beginning of the search term - that would be a good middle ground/option to have I think?
