### ISSUE TITLE
Extension stopped showing up in Safari

### ISSUE THREAD

**Issue by gubikmic** [arnemart/SafariKeywordSearch#7]
Hey thanks for building and publishing this extension!
It worked when I installed it but now it somehow stopped showing up inside of Safari → Settings → Extensions.
I reinstalled Keyword Search from the MAS but it didn't re-appear.
Is there any way to debug this?
Thanks!

Safari 14.0.3 on macOS 11.2.3

**Comment by arnemart** [comment]
I have heard from a couple other people who are also experiencing this. No idea what's causing it but I'm looking into it.

**Comment by shahrammaralani** [comment]
Same for me. It stopped since couple of days.

**Comment by neilio** [comment]
Same issue here. I've tried uninstalling and reinstalling but nothing has worked.

**Comment by mcg** [comment]
FWIW this works fine in Safari on Monterey public beta.

**Comment by arnemart** [comment]
Is this still a problem with version 2.0?

**Comment by arnemart** [comment]
Closing this now, please feel free to reopen it if it’s still happening.

**Comment by shahrammaralani** [comment]
Works now as expected. Thanks.

**Comment by arnemart** [comment]
Just had another report of this happening. Will keep investigating.

**Comment by ts** [comment]
This is happening to me on macOS 12.0.1 (21A559) on a new 14-inch M1 Pro machine. Worked fine on the M1 Air I migrated from. I've tried a few uninstall/re-installs to no avail. I'm likely going to wipe this machine in the next week to drop a new OS image on it but figured I'd chime in since it seems a bit of a phantom issue.

**Comment by ts** [comment]
> This is happening to me on macOS 12.0.1 (21A559) on a new 14-inch M1 Pro machine. Worked fine on the M1 Air I migrated from. I've tried a few uninstall/re-installs to no avail. I'm likely going to wipe this machine in the next week to drop a new OS image on it but figured I'd chime in since it seems a bit of a phantom issue.

Started working as expected today for no apparent reason. Happy to help troubleshoot further, but until then, thanks!

**Comment by arnemart** [comment]
Still completely stumped by this and have no idea how to even start debugging it. If I can think of anything I'll post it here.

**Comment by mr100percent** [comment]
I am also experiencing the same issue. I tried some basic debugging, reinstalling and then allowing unsigned extensions in Safari. It's still not working. Also, the standalone app does not launch extension preferences anymore either and I suspect there's a connection. This is Monterey 12.0.1 on an M1 Pro.

**Comment by sutrisno00** [comment]
Its annoying, it works on a new machine (M1 chip laptop) with the latest OS, and suddenly not working on old machine (iMac) with the latest OS.

The second step (by installing Safari Technical Preview) solve it 'magically'. Source : https://travismc.medium.com/how-to-fix-safari-app-extensions-not-appearing-in-safari-preferences-b3c897648eef

Hope it helps.

**Comment by jimpalompa** [comment]
I can confirm the same issue here. Weird glitch, since I have Keyword Search installed on two other macs, and they're working fine. All my three Macs are running macOS Monterey 12.0.1 but only one has problems with the extension loading, and does not appear in Safari preferences.

@sutrisno00 solution does work 'magically'. It will be my temporary fix for now.

As soon as I delete Safari Technology Preview.app from Applications folder, or uninstall it using a cleaner app, the extension disappears. So I have to keep Safari Technology Preview even though I am not using it.

**Comment by arnemart** [comment]
Thanks for all your comments. To me this strongly suggests a bug in Safari, and it seems to be happening to other extensions as well. Let’s hope the next Safari update fixes it.

**Comment by bahipara** [comment]
The fix that worked for me was to [rebuild Launch Services for Safari](https://lapcatsoftware.com/articles/disappearing-safari.html).

(Background: 14" Apple Silicon MacBook Pro 2021 running macOS Monterey 12.0.1, with Safari Keyword Search from the App Store working fine for a while. Disappeared this morning. Allowing unsigned extensions in the Develop menu didn't fix it and nor did a restart.)

**Comment by dmkishi** [comment]
> Thanks for all your comments. To me this strongly suggests a bug in Safari, and it seems to be happening to other extensions as well. Let’s hope the next Safari update fixes it.

I hope so too! 🤞

Just reporting in another incident and confirming the fix. I upgraded to Monterey this past Saturday, uninstalled Safari Technology Preview, and then didn't touch the computer till this Monday morning only to find Keyword Search inoperable. I did the usual dance of restarting Safari, the computer, uninstalling and reinstalling, etc., till I found this thread and reinstalled Safari Technology Preview, which magically did the trick (see screenshot attached below.)

Safari 15.1 on macOS 12.0.1 on M1 MacBook Air

![Screen Shot 2021-11-22 at 9 48 54 AM--convert](https://user-images.githubusercontent.com/1638880/142912329-82410e90-e51a-4c5f-8c89-10e76cebfb65.jpg)

**Comment by arnemart** [comment]
> The fix that worked for me was to [rebuild Launch Services for Safari](https://lapcatsoftware.com/articles/disappearing-safari.html).

Fantastic, thanks for the link.

**Comment by arnemart** [comment]
Putting the rebuild launch services trick in the readme and closing this issue.

**Comment by docwindsor** [comment]
I've also been having this issue for several months, across both Big Sur and Monterey. I tried un-installing, re-installing, rebooting, etc. and none of that worked. (Did not try Safari Preview version, however.) [Rebuilding the launch services for Safari](https://lapcatsoftware.com/articles/disappearing-safari.html) worked for me as well.
