### ISSUE TITLE
Deleted items reappear

### ISSUE THREAD

**Issue by amja** [arnemart/SafariKeywordSearch#8]
Deleting an item and then reopening the extension causes that item to reappear. Unless I am missing something, it looks like `KeywordSearchData.deleteSearch()` is missing a call to save the change in user defaults. The same is true of adding a new search without modifying but this could be expected behaviour.

Thanks :)

**Comment by arnemart** [comment]
Oh yeah, looks like you're right! I'll fix it in the next version

**Comment by arnemart** [comment]
Sorry for the wait, this is fixed i version 2 which will be out extremely shortly.
